version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  frontend:
    depends_on:
      - backend
    build: ./habit_frontend
    ports:
      - "3000:3000"
    volumes:
      - "./habit_frontend:/app"
  backend:
    depends_on:
      - mongo
    container_name: backend
    build: ./habit_backend
    ports:
      - "5656:5656"
    environment:
      - PORT=5656
      - DB_URL=mongodb://root:example@mongo:27017/
    volumes:
      - "./habit_backend:/backend"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
