name: Continuous Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Frontend Dependencies
        run: cd habit_frontend && npm ci
      - name: Perform Frontend Linting
        run: cd habit_frontend && npx eslint .
      - name: Perform Frontend Testing
        run: cd habit_frontend && npm t
