name: Continuous Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Frontend Lint Checks
        run: cd habit_frontend
      - name: Lint Action
        uses: wearerequired/lint-action@v2.0.1
        with:
          eslint: true
          prettier: true
      - run: echo "job is running"
