name: Continuous Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Frontend Lint Checks
        run: cd habit_frontend && npm ci
      - name: ESLINT
        run: cd habit_frontend && npm eslint .
      - run: echo "job is running"
