name: Continuous Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint Action
        uses: wearerequired/lint-action@v2.0.1
      - run: echo "job is running"
